name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SLUG: gr-iury-andrade
  PORTA: 23120

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Preparar a chave de deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy
          ssh-keyscan -H gr.lab.ayty.org >> ~/.ssh/known_hosts

      - name: Remover front antigo
        continue-on-error: true
        run: ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker rm front

      - name: Remover api antiga
        continue-on-error: true
        run: ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker rm api

      - name: Remover banco antigo
        continue-on-error: true
        run: ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker rm banco

      - name: Criar rede dados
        continue-on-error: true
        run: ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker network create dados --interna

      - name: Criar rede web
        continue-on-error: true
        run: ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker network create web

      - name: Criar volume pgdata
        continue-on-error: true
        run: ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker volume create pgdata

      - name: Subir banco, API e front
        run: |
          ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker run -d --name banco --network dados -v pgdata:/var/lib/postgresql/data -e POSTGRES_PASSWORD=${{ secrets.DB_SENHA }} -e POSTGRES_DB=pokedex postgres:17-alpine
          ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker run -d --name api --network dados -e POSTGRES_HOST=gr-iury-andrade-banco -e POSTGRES_DB=pokedex -e POSTGRES_PASSWORD=${{ secrets.DB_SENHA }} gr-atv2-api:1
          ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker network connect web api
          ssh -i ~/.ssh/deploy ${{ env.SLUG }}@gr.lab.ayty.org gr-docker run -d --name front --network web -p ${{ env.PORTA }}:80 -e API=gr-iury-andrade-api -e DEPLOY_SHA=${{ github.sha }} gr-atv2-front:1

      - name: Conferir que subiu
        run: |
          sleep 5
          curl -f http://gr.lab.ayty.org:${{ env.PORTA }}
